apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: z428uh2em-python 
  janus-idp.io/tekton: z428uh2em-python
  backstage.io/kubernetes-id: z428uh2em-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z428uh2em-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml